{% set version = "0.7.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-flextable
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/flextable_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/flextable/flextable_{{ version }}.tar.gz
  sha256: 571a644cf22fda5ad38c4bcc7e2f6355a96be1045cc7ffe8906a7c6e98475694

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-base64enc
    - r-data.table >=1.13.0
    - r-gdtools >=0.1.6
    - r-htmltools
    - r-knitr
    - r-officer >=0.3.19
    - r-rlang
    - r-rmarkdown
    - r-uuid >=0.1_4
    - r-xml2
  run:
    - r-base
    - r-base64enc
    - r-data.table >=1.13.0
    - r-gdtools >=0.1.6
    - r-htmltools
    - r-knitr
    - r-officer >=0.3.19
    - r-rlang
    - r-rmarkdown
    - r-uuid >=0.1_4
    - r-xml2

test:
  commands:
    - $R -e "library('flextable')"           # [not win]
    - "\"%R%\" -e \"library('flextable')\""  # [win]

about:
  home: https://davidgohel.github.io/flextable
  license: GPL-3.0-only
  summary: Create pretty tables for 'HTML', 'Microsoft Word' and 'Microsoft PowerPoint' documents.  Functions are provided to let users create tables, modify and format their content.  It extends package 'officer' that does not contain any feature for customized tabular reporting  and can be used within R markdown documents.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: flextable
# Type: Package
# Title: Functions for Tabular Reporting
# Version: 0.5.5
# Authors@R: c( person("David", "Gohel", role = c("aut", "cre"), email = "david.gohel@ardata.fr"), person("Quentin", "Fazilleau", role = c("ctb"), email = "quentin.fazilleau@ardata.fr"), person("Maxim", "Nazarov", role = c("ctb"), comment = "rmarkdown for docx output"), person(given = "Titouan", family = "Robert", role = c("ctb")) )
# Description: Create pretty tables for 'HTML', 'Microsoft Word' and 'Microsoft PowerPoint' documents.  Functions are provided to let users create tables, modify and format their content.  It extends package 'officer' that does not contain any feature for customized tabular reporting  and can be used within R markdown documents.
# License: GPL-3
# LazyData: TRUE
# Imports: stats, utils, grDevices, graphics, officer (>= 0.2.0), rmarkdown, knitr, htmltools, xml2, data.table, gdtools (>= 0.1.6), rlang, base64enc
# RoxygenNote: 6.1.1
# Suggests: testthat, xtable, magrittr, webshot, magick, ggplot2
# Encoding: UTF-8
# URL: https://davidgohel.github.io/flextable
# BugReports: https://github.com/davidgohel/flextable/issues
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-06-25 08:46:29 UTC; davidgohel
# Author: David Gohel [aut, cre], Quentin Fazilleau [ctb], Maxim Nazarov [ctb] (rmarkdown for docx output), Titouan Robert [ctb]
# Maintainer: David Gohel <david.gohel@ardata.fr>
# Repository: CRAN
# Date/Publication: 2019-06-25 09:20:03 UTC
