appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: AQjAyHWxymams4zXBfYesgOYGMNcoMi7tQfaUQRkJp1sKCDkxDlqUgUgBjrTxwVwQHgCPzYxmn4ntsybbFpJN/2LKFpPz4LHVoXYjBsInjb4zL63HlNyYfwLwx7Jg01teqrKiAxC7RQEICEUVj6CA2VwRxlJSaHDOQoPPhADH4Xjl/bWPjXYCp4zH4X37wu6u07OZ/nGBbe5g7MXGVvNW7/tWBGUfbTMIAF3Fcp2vkzCsyW8RG383eAsTG5Cn2cF0F0oiGxWxXprp6N4O1idFDjD/+uLNPymeL7w0ExfXnwCbSlgWfuwDEYKRtH2r/od+QnjSP8NFipHnpE5PWOUjARVQursFXjwxWtmBGHouYdUL6LKBdy/8Xt5Qb08eP7ZNQITZ2ElAkQiM8DUAHS5hpoaLl4bQbVjELnO0V8i0vs3GWfP0cidkHSj9bVAwV8TC+TA3rPLAfBUtI2BFFPTXiKvpUGmXjqwLrFymeeaQ1F4Q3fNUxPO3RD+KmZxSXxM5lN0rX8FCZBHUEPsT8eSTmJzlhxP7Xy+sjZFE4vzVxkMB38eRc3klsQYTYOXdJuNVTrGIqYKVw3+fcBAwngQKDJpP+EL82bz8lEbnoowtjNZPvbEtEmFMGiqW+TVTsaWgC69ARK4JjBW+zrdSB6XlULZKMrdtAiU2d/mhg/k3tE=}
